### ISSUE TITLE
README

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/cn-ccs-codes#2]
Needs readme saying where you got the codes from, and what they are.

**Comment by ronaldtse** [comment]
I was given a Word Doc from a contact that works with GB standards. Let's add a ticket to translate the description.

**Comment by ronaldtse** [comment]
Uploaded here. 

[中国标准文献分类法（中标分类CCS）.doc.zip](https://github.com/metanorma/cn-ccs-codes/files/5157434/CCS.doc.zip)
